### ISSUE TITLE
Styleswap512.pdparams seems to be missing

### ISSUE THREAD

**Issue by BeaverInGreenland** [Seanseattle/StyleSwap#7]
I tried to run `test.py` and I got the following error: 

```
Namespace(source_img_path='./examples/images/2.png', target_img_path='./examples/images/12012.png', output_path='results/test.png', size=512, align_source=False, align_target=False)
W1107 11:21:27.417249 22688 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W1107 11:21:27.535109 22688 device_context.cc:465] device: 0, cuDNN Version: 8.1.
.../anaconda3/envs/paddlepaddle/lib/python3.9/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File ".../StyleSwap/test.py", line 76, in <module>
    generator.set_dict(paddle.load('./checkpoints/styleswap512.pdparams'))
  File ".../anaconda3/envs/paddlepaddle/lib/python3.9/site-packages/paddle/framework/io.py", line 985, in load
    load_result = _legacy_load(path, **configs)
  File ".../anaconda3/envs/paddlepaddle/lib/python3.9/site-packages/paddle/framework/io.py", line 1003, in _legacy_load
    model_path, config = _build_load_path_and_config(path, config)
  File ".../anaconda3/envs/paddlepaddle/lib/python3.9/site-packages/paddle/framework/io.py", line 161, in _build_load_path_and_config
    raise ValueError(error_msg % path)
ValueError: The ``path`` (./checkpoints/styleswap512.pdparams) to load model not exists.
```

Can we download the missing checkpoints ? If so, how can we download them ?

**Comment by fanjc320** [comment]
same problem
